services:
  gitea-mcp:
    image: seepine/gitea-mcp:latest
    ports:
      - 3000:3000
    environment:
      # [可选] 配置后客户端传递的 Gitea-Host 请求头将无效
      GITEA_HOST: http://gitea.example.com

    # for dev
    build:
      context: .
      dockerfile: Dockerfile
